Repository FE-J1/taskify, pull requests merged in 2024-11, with the labels that each got.

#77 Feat: 댓글관련 기능 구현 완료
  components/Cards/Card.tsx
  components/Cards/CardDueDate.tsx
  components/Cards/CardImage.tsx
  components/Cards/CardList.tsx
  components/Cards/CardTags.tsx
  components/Comments/CommentInput.tsx
  components/Comments/CommentItem.tsx
  components/DashBoard/Column.tsx
  components/DashBoard/column/Column.tsx
  components/DashBoard/inputs/ImageInput.tsx
  components/DashBoard/inputs/TagInput.tsx
  components/DashBoard/todo/UpdateTodoForm.tsx
  components/DashBoardEdit/InviteeList.tsx
  components/DashBoardEdit/MemberList.tsx
  components/Layout/CardDetailModalLayout.tsx
  components/Layout/CardListLayout.tsx
  components/Layout/DashBoardLayout.tsx
  components/MyDashBoard/MyDashHdr.tsx
  components/MyDashBoard/MyDashList.tsx
  components/MyDashBoard/UnInvited.tsx
  components/UI/modal/CardModal/CardDetailModal.tsx
  components/UI/modal/CardModal/components/CardCommentList.tsx
  components/UI/modal/CardModal/components/CardHeader.tsx
  components/UI/modal/CardModal/components/CardSidebar.tsx
  components/UI/modal/CardModal/components/CardTagList.tsx
  components/UI/modal/CardModal/styles.tsx
  hooks/dashboard/useCardList.ts
  hooks/dashboard/useGetDashboardList.ts
  hooks/dashboard/useGetInvitedList.ts
  hooks/modal/useComments.ts
  hooks/modal/useModal.tsx
  hooks/useGetUser.tsx
  package-lock.json
  package.json
  pages/404.tsx
  pages/_app.tsx
  pages/cards/index.tsx
  pages/dashboards/[dashboardsId]/edit.tsx
  pages/dashboards/[dashboardsId]/index.tsx
  pages/signup.tsx
  public/images/icons/icon_chip_selected.svg
  store/authStore.ts
  store/invitationStore.ts
  store/tagColorStore.ts
  types/comments.ts
  types/users.ts
  utils/api/axiosInstanceApi.ts
  utils/api/cardsApi.ts
  utils/api/commentsApi.ts
  utils/api/cookie.ts
  utils/api/dashboardsApi.ts
  utils/api/userApi.ts
Labels: ✨ feature

#87 Feat : 초대하기 모달 구현
  components/DashBoardEdit/InviteeList.tsx
  components/DashBoardEdit/MemberList.tsx
  components/Layout/ModalLayout.tsx
  components/MyDashBoard/MyDashHdr.tsx
  components/UI/pagination/Pagination.tsx
  pages/dashboards/[dashboardsId]/edit.tsx
  pages/dashboards/[dashboardsId]/index.tsx
  public/images/icons/icon_add_box_white.svg
  public/images/icons/icon_chip_selected.svg
  store/dashBoardStore.ts
Labels: ✨ feature

#89 Feat: avatar group 기능 구현
  components/MyDashBoard/AvatarGroup.tsx
  components/MyDashBoard/MyDashHdr.tsx
  hooks/dashboard/useResponsiveThreshold.ts
  types/dashboards.ts
  utils/api/dashboardsApi.ts
Labels: 🙋‍♂️ help wanted, ✨ feature, 🎨 design

#91 Fix: 항상 동적클래스를 사용하도록 safelist 옵션 추가
  components/DashBoard/inputs/ColorInput.tsx
  components/MyDashBoard/CreateDashBoard.tsx
  package-lock.json
  types/color.ts
Labels: 🐞 bug

#96 Feat: useErrorModal을 통한 에러메시지 관리
  components/DashBoardEdit/InviteeList.tsx
  components/DashBoardEdit/MemberList.tsx
  components/My/MyPassWord.tsx
  components/MyDashBoard/InvitedList.tsx
  components/MyDashBoard/MyDashHdr.tsx
  hooks/modal/useErrorModal.tsx
  pages/dashboards/[dashboardsId]/edit.tsx
  pages/dashboards/[dashboardsId]/index.tsx
  pages/login.tsx
  pages/signup.tsx
  store/authStore.ts
  utils/api/authApi.ts
Labels: ✨ feature

#101 Refactor(92) : 회원가입 성공 시 로그인 화면으로 이동
  components/UI/modal/ModalAlert.tsx
  pages/login.tsx
  pages/signup.tsx
  utils/api/authApi.ts
  utils/api/error.ts
Labels: 🐞 bug, 🚀 enhancement

#97 Feat(#79): 컬럼 수정 삭제 구현 완료
  components/DashBoard/Column.tsx
  components/DashBoard/column/Column.tsx
  components/DashBoard/column/ColumnHeader.tsx
  components/DashBoard/inputs/UserInput.tsx
  components/DashBoard/todo/TodoTagList.tsx
  components/MyDashBoard/AvatarGroup.tsx
  components/MyDashBoard/MyDashHdr.tsx
  components/MyDashBoard/MyDashSideMenu.tsx
  components/UI/modal/InputModal/OneInputModal.tsx
  hooks/modal/useModal.tsx
  next.config.mjs
  pages/404.tsx
  pages/api/auth/login.ts
  pages/api/auth/userInfo.ts
  pages/dashboards/[dashboardsId]/edit.tsx
  pages/dashboards/[dashboardsId]/index.tsx
  pages/login.tsx
  types/columns.ts
  utils/api/columnsApi.ts
  utils/api/dashboardsApi.ts
Labels: ✨ feature

#102 Refactor: Card의 상태 변경 시, 화면에 즉시 반영
  components/Cards/Card.tsx
  components/Cards/CardImage.tsx
  components/Cards/CardList.tsx
  components/DashBoard/column/Column.tsx
  components/DashBoard/column/ColumnHeader.tsx
  components/DashBoard/todo/CreateTodoForm.tsx
  components/DashBoard/todo/UpdateTodoForm.tsx
  components/Layout/CardListLayout.tsx
  components/UI/modal/CreateTodoModal.tsx
  components/UI/modal/UpdateTodoModal.tsx
  hooks/dashboard/useCardList.ts
  pages/dashboards/[dashboardsId]/index.tsx
  store/columnStore.ts
  store/dashBoardStore.ts
  types/dashboards.ts
  utils/TodoForm.ts
Labels: 🛠️ refactor

#104 #90 대쉬보드 색상 표기 오류 수정
  components/DashBoard/inputs/ColorInput.tsx
  components/MyDashBoard/MyDashSideMenu.tsx
Labels: 🐞 bug, 🚀 enhancement

#106 Bug(105) : 모달 팝업 시 아바타 그룹이 하이라이트 되는 오류
  components/MyDashBoard/AvatarGroup.tsx
Labels: 🐞 bug, 🎨 style

#107 Refactor: serversideProps를 사용하여 각 페이지별 접근 제어 기능 구현
  pages/dashboards/[dashboardsId]/edit.tsx
  pages/index.tsx
  pages/login.tsx
  pages/my/index.tsx
  pages/mydashboard/index.tsx
  pages/signup.tsx
Labels: ✨ feature, 🛠️ refactor

#108 Chore: 각 페이지 UI 개선 작업
  components/DashBoard/column/Column.tsx
  components/DashBoardEdit/components/MemberItem.tsx
  components/Layout/CardListLayout.tsx
  components/Layout/DashBoardLayout.tsx
  components/MyDashBoard/CreateDashBoard.tsx
  components/UI/modal/CardModal/CardDetailModal.tsx
  pages/dashboards/[dashboardsId]/index.tsx
  styles/globals.css
Labels: 🎨 style

#109 Feat: 댓글 본인만 수정, 삭제 / 모달 kebab, close svg 수정
  components/Comments/CommentItem.tsx
  components/MyDashBoard/invitationsList/InvitationList.tsx
  components/UI/modal/CardModal/components/CardHeader.tsx
  components/UI/modal/CardModal/styles.tsx
  components/UI/modal/InputModal/OneInputModal.tsx
  hooks/useObserver.tsx
  public/images/icons/icon_close.svg
  public/images/icons/icon_kebab.svg
  public/images/icons/icon_kebab_more.svg
Labels: 🚀 enhancement

#112 Fix: 빌드 오류 해결
  components/Comments/CommentInput.tsx
  components/Layout/DashBoardLayout.tsx
  components/MyDashBoard/AvatarGroup.tsx
  components/UI/dropdown/Dropdown.tsx
  components/UI/modal/CardModal/CardDetailModal.tsx
  components/UI/modal/CardModal/styles.tsx
  hooks/dashboard/useGetInvitedList.ts
  pages/index.tsx
  pages/login.tsx
  pages/signup.tsx
Labels: 🐞 bug

#114 Refactor: modalAlert type 추가
  components/DashBoard/column/ColumnHeader.tsx
  components/DashBoardEdit/InviteeList.tsx
  components/UI/modal/ModalAlert.tsx
Labels: 🛠️ refactor

#134 refactor: column type 에러 수정 및 중복 타입선언 제거
  store/dashBoardStore.ts
  types/columns.ts
  utils/api/columnsApi.ts
Labels: 🐞 bug, 🛠️ refactor
