Repository FE-J1/taskify, pull requests merged in 2024-10, with the labels that each got.

#18 Feat: mydashboard 구현
  components/Layout/DashBoardLayout.tsx
  components/MyDashBoard/DashBoardLink.tsx
  components/MyDashBoard/InvitedList.tsx
  components/MyDashBoard/MyDashHdr.tsx
  components/MyDashBoard/MyDashList.tsx
  components/MyDashBoard/MyDashSideMenu.tsx
  components/MyDashBoard/MyDashStyle.tsx
  components/MyDashBoard/UnInvited.tsx
  hooks/dashboard/useGetDashboardList.ts
  hooks/dashboard/useGetInvitedList.ts
  hooks/useGetUser.tsx
  package-lock.json
  pages/index.tsx
  pages/login/index.tsx
  pages/mydashboard/index.tsx
  public/images/icons/icon_add_card.svg
  public/images/icons/pagination_left.svg
  public/images/icons/pagination_right.svg
  public/images/resource/uninvited_image.png
  types/invitedList.ts
  types/users.ts
Labels: 🎨 style, ✨ feature

#20 Feat: ModalCard 컴포넌트 생성
  components/UI/modal/ModalCard.tsx
  pages/api/axiosInstanceApi.ts
  pages/api/cardsApi.ts
  pages/api/columnsApi.ts
  pages/api/dashboards.ts
  pages/api/dashboardsApi.ts
  pages/cards/index.tsx
  pages/dashboards/[dashboardsId].tsx
  pages/dashboards/index.tsx
  pages/login/index.tsx
  public/images/icons/icon_close.svg
  public/images/icons/icon_kebab.svg
  types/cards.ts
  types/columns.ts
  types/dashboards.ts
Labels: 🎨 style, 📬 api

#21 Feat: my페이지 UI 구현
  components/My/InputField.tsx
  components/My/MyButton.tsx
  components/My/MyPassWord.tsx
  components/My/MyProfile.tsx
  components/MyDashBoard/DashBoardLink.tsx
  components/MyDashBoard/MyDashList.tsx
  hooks/dashboard/useGetDashboardList.ts
  hooks/dashboard/useGetInvitedList.ts
  hooks/useGetUser.tsx
  package-lock.json
  pages/dashboards/index.tsx
  pages/my/index.tsx
  public/images/icons/profile_add_box.svg
  test.http
  types/my.ts
Labels: 🎨 style, 🎨 design

#26 Feature: 대시보드 상세 및 칼럼 목록 구현
  components/Cards/CardList.tsx
  components/DashBoard/Column.tsx
  components/MyDashBoard/InvitedList.tsx
  next.config.mjs
  pages/cards/index.tsx
  pages/dashboards/[dashboardsId].tsx
  public/images/icons/icon_add_column.svg
Labels: 🎨 design, 📬 api

#28 feat(14) : 회원가입 UI 및 유효성 검사 기능 완성
  components/Auth/Input.tsx
  components/Auth/Logo.tsx
  hooks/useInput.tsx
  package-lock.json
  package.json
  pages/api/authApi.ts
  pages/login.tsx
  pages/login/index.tsx
  pages/signup.tsx
  utils/validation.ts
Labels: 🎨 style, ✨ feature

#33 Feature/modal alert
  components/My/InputField.tsx
  components/My/MyButton.tsx
  components/My/MyPassWord.tsx
  components/My/MyProfile.tsx
  components/UI/modal/ModalAlert.tsx
  hooks/useModalAlert.tsx
Labels: ✨ feature, 🎨 design

#40 Feat: 할 일 생성 Modal 구현
  components/DashBoard/Column.tsx
  components/DashBoard/TodoButton.tsx
  components/DashBoard/TodoForm.tsx
  components/DashBoard/TodoTagList.tsx
  components/DashBoard/styles.tsx
  components/Layout/ModalLayout.tsx
  components/My/MyPassWord.tsx
  components/My/MyProfile.tsx
  components/MyDashBoard/MyDashList.tsx
  components/UI/modal/CreateTodoModal.tsx
  components/UI/modal/ModalAlert.tsx
  hooks/dashboard/useImagePreview.tsx
  hooks/useModal.tsx
  package-lock.json
  package.json
  public/images/icons/icon_x_round.svg
  styles/globals.css
  types/columns.ts
  types/dashboards.ts
  utils/TodoForm.tsx
  utils/api/columnsApi.ts
Labels: ✨ feature

#45 Feat: 할 일 생성 Modal API 연결
  components/Cards/CardList.tsx
  components/DashBoard/Column.tsx
  components/DashBoard/ImageUpload.tsx
  components/DashBoard/TodoForm.tsx
  components/DashBoard/TodoTagList.tsx
  components/DashBoard/inputs/DateInput.tsx
  components/DashBoard/inputs/DescriptionInput.tsx
  components/DashBoard/inputs/TagInput.tsx
  components/DashBoard/inputs/TitleInput.tsx
  components/DashBoard/inputs/UserInput.tsx
  components/UI/modal/CreateTodoModal.tsx
  components/UI/modal/ModalPotal.tsx
  pages/dashboards/[dashboardsId].tsx
  types/dashboards.ts
  utils/TodoForm.tsx
  utils/api/dashboardsApi.ts
Labels: ✨ feature

#44 Feat: zustand로 authStore 상태 관리
  components/Cards/CardList.tsx
  components/UI/modal/InputModal/OneInputModal.tsx
  package-lock.json
  package.json
  pages/cards/index.tsx
  pages/dashboards/[dashboardsId].tsx
  pages/login.tsx
  store/authStore.ts
  utils/api/authApi.ts
Labels: 🚀 enhancement

#52 Feat : 새로운 대시보드 생성
  components/Auth/Input.tsx
  components/DashBoard/inputs/ColorInput.tsx
  components/MyDashBoard/CreateDashBoard.tsx
  components/MyDashBoard/MyDashList.tsx
  package.json
  public/images/icons/icon_select.svg
  styles/globals.css
  tailwind.config.ts
  types/color.ts
  types/dashboards.ts
  utils/api/authApi.ts
  utils/api/dashboardsApi.ts
  utils/api/error.ts
Labels: 🎨 style, ✨ feature, 📬 api

#54 Fix(#53) : 올바른 값을 입력시 로그인 버튼 색상 보라색으로 변환
  pages/login.tsx
Labels: 🚀 enhancement, 🎨 style

#57 Feat: 카드 클릭 시 카드 상세 모달 오픈 (실제 데이터로 수정)
  components/Cards/CardList.tsx
  components/DashBoard/Column.tsx
  components/My/MyPassWord.tsx
  components/MyDashBoard/.MyDashList.tsx.swp
  components/MyDashBoard/MyDashHdr.tsx
  components/MyDashBoard/MyDashList.tsx
  components/MyDashBoard/MyDashSideMenu.tsx
  components/UI/modal/CardModal/CardDetailModal.tsx
  hooks/modal/useCardDetailModal.ts
  hooks/modal/useModal.tsx
  hooks/modal/useOneInputModal.ts
  hooks/useModal.tsx
  package-lock.json
  package.json
  pages/Landing/LandingBanner.tsx
  pages/_app.tsx
  pages/api/auth/login.ts
  pages/api/auth/userInfo.ts
  pages/dashboards/[dashboardsId].tsx
  pages/login.tsx
  public/images/logos/logo-large.svg
  store/authStore.ts
  utils/api/authApi.ts
  utils/api/axiosInstanceApi.ts
  utils/api/cookie.ts
Labels: ✨ feature

#60 Feat: CardDetailModal 삭제기능 구현
  components/Cards/CardList.tsx
  components/Cards/components/Card.tsx
  components/Cards/components/CardDueDate.tsx
  components/Cards/components/CardImage.tsx
  components/Cards/components/CardTags.tsx
  components/DashBoard/todo/UpdateTodoForm.tsx
  components/UI/modal/CardModal/CardDetailModal.tsx
  components/UI/modal/CardModal/components/CardHeader.tsx
  utils/api/cardsApi.ts
Labels: ✨ feature

#66 Feat: MyProfile 상태 관리 기능 추가
  components/My/MyProfile.tsx
  store/profileStore.ts
  types/my.ts
  utils/api/authApi.ts
Labels: ✨ feature

#75 Fix: 할 일 생성, 수정, 삭제 시, 변경사항이 즉시 화면에 반영 #74
  components/Cards/CardList.tsx
  components/DashBoard/Column.tsx
  components/DashBoard/column/AddCardButton.tsx
  components/DashBoard/column/Column.tsx
  components/DashBoard/column/ColumnHeader.tsx
  components/DashBoard/todo/CreateTodoForm.tsx
  components/DashBoard/todo/UpdateTodoForm.tsx
  components/Landing/Card.tsx
  components/Landing/LandingBanner.tsx
  components/Landing/LandingFooter.tsx
  components/Landing/LandingHeader.tsx
  components/Landing/LandingInfo.tsx
  components/Landing/LandingLayout.tsx
  components/Landing/styles.tsx
  components/My/MyProfile.tsx
  components/UI/modal/CreateTodoModal.tsx
  components/UI/modal/UpdateTodoModal.tsx
  pages/dashboards/[dashboardsId]/index.tsx
  pages/index.tsx
  store/cardsStore.ts
  store/profileStore.ts
  types/dashboards.ts
  utils/api/authApi.ts
Labels: 🛠️ refactor

#84 Feat: 로딩 스피너 구현
  components/My/MyProfile.tsx
  components/MyDashBoard/InvitedList.tsx
  components/UI/loading/Loading.tsx
  components/UI/loading/LoadingSpinner.tsx
  package-lock.json
  package.json
  pages/dashboards/[dashboardsId]/index.tsx
  pages/my/index.tsx
Labels: 🎨 style
